[bazel_sdk][tests] Update to platforms version 0.0.10
Update the version of the @platforms repository being used.
Without that, the following error occurs when trying to run
`bazel` directly in `//build/bazel_sdk/tests`:

```
ERROR: Error computing the main repository mapping: at /usr/local/google/home/digit/.cache/bazel/_bazel_digit/fec004571c1331a01694de96006458ce/external/fuchsia_workspace/fuchsia/deps.bzl:22:5: at /usr/local/google/home/digit/.cache/bazel/_bazel_digit/fec004571c1331a01694de96006458ce/external/fuchsia_workspace/fuchsia/workspace/rules_fuchsia_deps.bzl:13:6: Label '@@platforms//host:extension.bzl' is invalid because 'host' is not a package; perhaps you meant to put the colon here: '@@platforms//:host/extension.bzl'?
```

Change-Id: I9e08e5bbec1a9eff05ef60b1631317f906b4f957
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1127253
Reviewed-by: Jiaming Li <lijiaming@google.com>
Fuchsia-Auto-Submit: David Turner <digit@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>