[fx] Verify effectiveness of `-d`.
Check if `-d` is ever overridden by a ffx configuration level default
target, and fail early if that's the case.

Example:
```
❯ fx -d fx-device serve
ERROR: The build level device "fx-device" is being overridden by the user level device "ffx-device".
ERROR: Here are all of the ffx default values set: [
  "ffx-device",
  [
    "fx-device"
  ]
]
ERROR: Please run `ffx target default unset; ffx target default unset --level global` to fix this.
```

Also removes `TEST_getdeviceaddr_name_looks_like_ipv4` since the
expected behavior of this test doesn't align with how ffx works in
reality (i.e `fx -d 1.1.244 ffx target default get` yields `1.1.244`
instead of `127.0.0.1`).

Diff of HEAD^ vs HEAD of this CL for non-CQ tests:
https://diff.googleplex.com/#key=PElcE3cttVvE

Fixed: 398268415
Change-Id: Ie83884c3e5cd96b8acb8e99d7f472d7d7de68d3c
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1214024
Commit-Queue: Darren Chan <chandarren@google.com>
Reviewed-by: Christopher Johnson <crjohns@google.com>
Reviewed-by: Clayton Wilkinson <wilkinsonclay@google.com>
Reviewed-by: Chase Latta <chaselatta@google.com>