[fuchsia-controller] Fix returning Sockets from FIDL methods.
This adds testing to ensure that decoding sockets works as intended.
This also adds some additional debugging code that was not in place
previously.

Without this code we would get an exception for attempting to convert a
u64::INT_MAX into a u32 which would look like the following:

```
OverflowError: Value 18446744073709551615 too large for u32
```

crjohns@ found a quick solution to this issue at fxr/1266793 and this
change adds some testing to prevent regression.

Fixed: 415380059

Change-Id: I239c7ff42874f3f1fcb05b2ce4a24e0c6a6a636c
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1267168
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Reviewed-by: Christopher Johnson <crjohns@google.com>
Fuchsia-Auto-Submit: Andrew Davies <awdavies@google.com>