[build][dtc] Restructure dtc compilation and parse errors
This simplifies the dtc actions by removing dtc.sh and moving to a
python scrupt that handles calling 'dtc' and also parses errors &
warnings to provide additional context.

Example:
```
Error: gen/path/to/a/dtsi/dts-example.dtsi:1.10-17 syntax error
FATAL ERROR: Unable to parse input tree
    1: &reserved-memory {
                ^---- syntax error
    2:  gpu_region: gpu_region@0 {
    3:   reg = <0x00 0x01234567 0x00 0x2000>;
    4:   no-map;
    5:  };
    6: };
```

This provides context for the error along with an indicator of the exact
line and character the error occurs.

Change-Id: I68b598e455d27e6381348bb3d709011dedaea28d
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1213986
Reviewed-by: Aaron Wood <aaronwood@google.com>
Reviewed-by: Suraj Malhotra <surajmalhotra@google.com>
Commit-Queue: Christopher Anderson <cja@google.com>