Revert "[funnel] add macOS deprecation warnings"
This reverts commit 0e1bb902c36f011818e12df85aa6c1b4a6cf75d4.

Reason for revert: broke Mac SDK builders:

  [19465/19502](1) ACTION //tools/docsgen:invoke_clidoc(//build/toolchain/fuchsia:x64)
  Error: Unable to write generate doc for "/Volumes/Work/s/w/ir/x/w/fuchsia/out/not-default/host_x64/funnel" to "gen/tools/docsgen/docs"

  Caused by:
      Error running help: Unexpected non-zero error code with tool "/Volumes/Work/s/w/ir/x/w/fuchsia/out/not-default/host_x64/funnel"
                and subcommands ["Cleans"].

Bug: 419875606
Original change's description:
> [funnel] add macOS deprecation warnings
>
> Prints out a message about this tools deprecation on mac.
>
> Bug: 419875606
> Change-Id: I08d8f4bae6381c1c37fc8773f815c05ab4c27106
> Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1284253
> Commit-Queue: Chase Latta <chaselatta@google.com>
> Reviewed-by: Colin Nelson <colnnelson@google.com>

Bug: 419875606
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I5b0d7b8d31309260171d72d0dd4ded207febda57
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1288344
Reviewed-by: RubberStamper 🤖 <android-build-ayeaye@system.gserviceaccount.com>
Fuchsia-Auto-Submit: Oliver Newman <olivernewman@google.com>
Commit-Queue: Oliver Newman <olivernewman@google.com>