[flake][components][bootfs] Fix flake
This test launches component_manager and then checks some state. It
assumes that component_manager continues running. However, this
assumption is not necessarily correct, because the root component it is
launching (hello_world) exits, whereupon component_manager will exit as
well. If component_manager exits before the test completes, something
else in the test may bind to an exposed capability (RealmQuery), causing
component_manager to restart. When it restarts, it does so implicitly
without its bootfs vmo argument, triggering this panic:

```
[00718.630551][1113][1198][coll:auto-48b1cae71e3d3107] WARN: thread 'main' panicked at ../../src/sys/component_manager/src/main.rs:108:51:
[00718.630595][1113][1198][coll:auto-48b1cae71e3d3107] WARN: Failed to create Rust bootfs: InvalidHandle { handle_type: BootfsVmo }
```

To fix, switch to a different root component (trigger.cml) that does not
exit.

Multiply: fuchsia-boot-resolver-integration-tests: 200

Fixed: 356731816
Change-Id: Iad5aaa8765538e6c9e467e42de025caba968d7b4
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1096960
Reviewed-by: Caslyn Tonelli <caslyn@google.com>
Commit-Queue: Gary Bressler <geb@google.com>