Reland "[ffx] Support Overnet over VSOCK"
This reverts commit 75119786b8db5ba0ad579ce517343cf3413aa358.

Reason for revert: We can just modify the change to not use that flag

Original change's description:
> Revert "[ffx] Support Overnet over VSOCK"
>
> This reverts commit d4e36c68f96d46b63ea8d24063235a4fa031aa30.
>
> Reason for revert:
> error[E0599]: no associated item named `SOCK_NONBLOCK` found for struct `SockFlag` in the current scope
>   --> ../../src/developer/ffx/daemon/target/src/overnet/vsock.rs:25:27
>    |
> 25 |     let flags = SockFlag::SOCK_NONBLOCK;
>    |                           ^^^^^^^^^^^^^ associated item not found in `SockFlag`
>
> Original change's description:
> > [ffx] Support Overnet over VSOCK
> >
> > Change-Id: I7411be0e1f2a54074bf5c5fd58c1e89516248262
> > Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1215428
> > Reviewed-by: Steven Grady <slgrady@google.com>
> > Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
> > Fuchsia-Auto-Submit: Casey Dahlin <sadmac@google.com>
>
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Change-Id: Ie270f23667409b08913d1e1ca0da2dc03949ff61
> Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1239264
> Reviewed-by: RubberStamper 🤖 <android-build-ayeaye@system.gserviceaccount.com>

Change-Id: Ib2c2c076f0521d66098aeced83df74472dc01082
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1238828
Fuchsia-Auto-Submit: Casey Dahlin <sadmac@google.com>
Reviewed-by: Ben Lawson <benlawson@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Reviewed-by: Steven Grady <slgrady@google.com>