[bazel] bazel_action.py: Add @rules_python_internal to the list of ignored repositories
This is necessary to roll rules_python-0.36 with tqr/915970.
Without this change, the build will fail with an error that looks
like:

```
ERROR: Found ignored external repository files:
  @@rules_python_internal//:py_internal.bzl
  @@rules_python_internal//:rules_python_config.bzl

These files are likely generated by a Bazel repository rule which has
no associated content hash file. Due to this, Bazel may regenerate them
semi-randomly in ways that confuse Ninja dependency computations.
```

In the future, we may have significantly more ignorable repositories
like this one, and their list will probably not be hard-coded in the
script, but determined by the workspace setup script. For now, this
small CL will do.

Bug: 381934267
Change-Id: I3b518b81dfd026556621539cc2808ee621f766a4
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1169054
Fuchsia-Auto-Submit: David Turner <digit@google.com>
Reviewed-by: David Fang <fangism@google.com>
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>