[memory] fix overflow panic in `ffx profile memory components` output
The way the kernel accounts and reports statistics changed in
https://fxrev.dev/1059692 . Due to this change, the calculation of
removing zram from reported "Other" is no longer correct, resulting in a
negative value, triggering overflow panic.

```
thread 'main' panicked at ../../src/developer/ffx/plugins/profile/memory/components/src/output.rs:351:55:
attempt to subtract with overflow
```

This patch fixes this by removing the subtraction: we're now
printing the kernel stats as we receive them, fixing the crash and
simplifying the logic.

Bug: 377258904
Change-Id: Ifc825a98f6cfe3d6b74a46d108c41ec888f17011
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1150254
Commit-Queue: Przemek Pietrzkiewicz <ppi@google.com>
Reviewed-by: Pierre Labatut <plabatut@google.com>