[Honeydew] Add time based verification for idle-suspend-auto-resume
idle-suspend-auto-resume uses `ffx starnix console` command to put the
device in susend mode. This command is blocked until the system resumes.
However as reported in b/331685794, this was broken. Since Honeydew
affordance solely relies on this command, Lacewing test could not catch
this failure. So adding time based verification to ensure
idle-supend-auto-resume command takes at-least 5 seconds.

With this CL, test will fail with below error:
honeydew.errors.SystemPowerStateControllerError: Putting the 'fuchsia-c863-1470-ae76' into 'IdleSuspend' followed by 'AutomaticResume after 5sec' operation took 0.10734724998474121 seconds instead of 5 seconds.

Verified the following on Patchset: 4
* Honeydew code guidelines
* Successfully ran the impacted functional tests using InfraRun
* Successfully ran Honeydew builders using try-jobs

Change-Id: I61a5a4a1450584cbdc0c9ae418bfb37f4cf3f82a
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1020156
Commit-Queue: Pavan Kumar Juturu <jpavankumar@google.com>
Reviewed-by: Christopher Johnson <crjohns@google.com>