[src/lib/fuchsia] Improve compile error output.
The transformer crate goes through a bunch of effort to avoid
panics and to use errors that can be turned into compiler errors
which preserve spans. But the proc macro entry points were
unwrapping those results instead of passing them back to rustc
as compiler errors.

Replaces

```
error: custom attribute panicked
  --> ...
   |
25 | #[fuchsia::main(logging_tags=["...", threads=2])]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: called `Result::unwrap()` on an `Err` value: Error("expected string literal")
```

with

```
error: expected string literal
  --> ...
   |
25 | #[fuchsia::main(logging_tags=["...", threads=2])]
   |                                      ^^^^^^^
```

And should similarly improve other compiler errors.

Change-Id: I01771d634fa9f8e1ed2ee66d090f5f5c28e81908
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1235171
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Fuchsia-Auto-Submit: Adam Perry <adamperry@google.com>
Reviewed-by: Miguel Flores <miguelfrde@google.com>