[fx] Ensure `fx bazel` runs with the right RBE wrappers.
Refactor fx-run-ninja into a new fx-run-build-command  function
which can be used to either run Ninja or Bazel commands in the
same way, which means:

- Setting environment variables properly for remote builds to work.
- Prepending an RBE wrapper script if needed.
- Collect system profile data if BUILD_PROFILE_ENABLED is set.

Then ensure that fx-bazel uses fx-run-build-command to run
Bazel. This fixes an issue where the command:

```
fx bazel build --config=host --config=remote //build/bazel/examples/hello_world
```

Would fail with:

```
ERROR: Failed to query remote execution capabilities: UNAVAILABLE: Credentials failed to obtain metadata
ERROR: ..../hello_world/BUILD.bazel:5:10: Compiling build/bazel/examples/hello_world/main.cc failed: (Exit 34): UNAVAILABLE: Credentials failed to obtain metadata
```

This also makes `fx bazel` invocations closer to how Bazel is
invoked from Ninja through bazel_action() and bazel_action.py,
though more work is needed to get a better match.

+ Simplify template.bazelrc a little since now cquery and aquery
  commands properly inherit "build" settings.

+ Ensure gcertauth also works with query commands. Otherwise
  `fx bazel query ...` would fail with an error, because our
  launcher script appends `--config=gcertauth` to all commands.

Change-Id: I15d37d8e0e53e3e350d3cc29387a4c017fdd38a0
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1269984
Reviewed-by: Oliver Newman <olivernewman@google.com>
Reviewed-by: David Fang <fangism@google.com>
Commit-Queue: David Turner <digit@google.com>