[proc][magma] Remove --size_t-is-usize
Needed because of bindgen update to fix:

error: unexpected argument '--size_t-is-usize' found

Change-Id: Ie7f1e082a76ea6192b15057136f098e2480ea43a
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/813826
Commit-Queue: Craig Stout <cstout@google.com>
Reviewed-by: James Robinson <jamesr@google.com>
Fuchsia-Auto-Submit: Craig Stout <cstout@google.com>
Reviewed-by: John Bauman <jbauman@google.com>