[sysmgr] Remove invalid FIDL call
This was missed in commit 4b50ae56b33124d066bfdff8ff750308e705cd28; the
result is that this log line appears on every boot:

ERROR: [../../sdk/lib/fidl/cpp/internal/proxy_controller.cc(61)] fidl validating error: message is missing a non-nullable handle. message: fuchsia.sys/EnvironmentGetDirectoryRequest, 24 bytes, 0 handles

This removes this invalid call.

Change-Id: I47fcbb3dca11cf80de8113bdd00762fae12193a4
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/821149
Fuchsia-Auto-Submit: Tamir Duberstein <tamird@google.com>
Commit-Queue: Tamir Duberstein <tamird@google.com>
Reviewed-by: Gary Bressler <geb@google.com>
Reviewed-by: Justin Mattson <jmatt@google.com>