[cmc] Make output required
`cmc compile` will panic if output is not provided, so make
the field mandatory.

See the new output:

$ ./out/default/host-tools/cmc compile examples/tests/rust/meta/temp_user.cml
error: The following required arguments were not provided:
    --output <output>

USAGE: cmc compile <FILE> --includepath <includepath>... --includeroot <includeroot> --output <output>

Fixed: b/297312018
Change-Id: Ib58ad36afe806c16e4d16c012ee32ed2e9e76cba
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/999914
Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
Reviewed-by: Amanda Tait <atait@google.com>
Reviewed-by: Gary Bressler <geb@google.com>
Fuchsia-Auto-Submit: David Gilhooley <dgilhooley@google.com>