[trace] Properly Terminate in Rust Trace Benchmark
Fully terminate the trace after finishing instead of just stopping.

Previously, tests running after the microbenchmark tests would emit log
messages such as:
```
INFO: [trace_manager.cc(73)] Controller is gone, terminating trace
ERROR: [src/performance/trace_manager/trace_manager.cc(94)] Ignoring initialize request, trace already initialized
ERROR: [src/performance/trace_manager/tracee.cc(404)] #27 {37875:ktrace_provider}: Failed to write provider info record to trace.
ERROR: [src/performance/trace_manager/trace_session.cc(441)] Encountered unrecoverable error writing socket
```
After this change, these no longer occur.

Bug: 135955
Bug: 135953
Change-Id: Ib8268bc141a1a546bb5cbe9a75ab399225a77d20
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/939205
Reviewed-by: Mark Seaborn <mseaborn@google.com>
Commit-Queue: Gwen Mittertreiner <gmtr@google.com>