[memory][scripts] Replace cgi with html
The treemap script currently fails with the error:
AttributeError: module 'cgi' has no attribute 'escape'

It also displays a warning message:
DeprecationWarning: 'cgi' is deprecated and slated for removal

The cgi module is only being used to do some string escaping. The html module contains an escape function that we can use. This change replaces
the cgi module with the html module in the treemap.py script.

Tests: manually ran the command from
https://fuchsia.dev/fuchsia-src/development/kernel/memory/memory?visualize_memory_usage#visualize_memory_usage

Change-Id: I01de93500fcd25bab0be374461924dde66e19a75
Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/983478
Reviewed-by: Joshua Seaton <joshuaseaton@google.com>
Commit-Queue: Novin Changizi <novinc@google.com>